CREATE TABLE enterprises (
  id BIGSERIAL PRIMARY KEY,
  uuid VARCHAR(64) UNIQUE,
  address TEXT NOT NULL,
  timezone VARCHAR (255),
  company VARCHAR (255) NOT NULL,
  communication_channel _VARCHAR,
  cnpj VARCHAR (14) NOT NULL UNIQUE,
  corporate_reason VARCHAR (255) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'enabled',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);