CREATE TABLE partners (
    id SERIAL PRIMARY KEY,
    uuid VARCHAR(64) UNIQUE,
    email VARCHAR(60) NOT NULL UNIQUE,
    document VARCHAR(14) NOT NULL UNIQUE,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL
)