CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  uuid VARCHAR(64) UNIQUE, 
  optin BOOLEAN,
  nickname VARCHAR(30),
  full_name VARCHAR (70),
  document VARCHAR (30) UNIQUE,
  password VARCHAR(40) NOT NULL,
  last_name VARCHAR (30) NOT NULL,
  first_name VARCHAR (30) NOT NULL,
  email VARCHAR (40) UNIQUE NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'enabled',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);